controller_manager:
  ros__parameters:
    update_rate: 200 #Hz
    use_sim_time: true

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    position_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

position_trajectory_controller:
  ros__parameters:
    joints:
      - base_to_shoulder_joint
      - shoulder_to_arm_joint
      - arm_to_elbow_joint
      - elbow_to_forearm_joint
      - forearm_to_wrist_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
